:github-address: https://github.com/hazelcast-guides/hazelcast-hibernate-springboot
:templates-url: https://raw.githubusercontent.com/hazelcast-guides/adoc-templates/master
:hazelcast: Hazelcast IMDG
:framework: Spring Boot

= Getting Started with Hazelcast and Hibernate Second-Level Cache

This guide will get you started to use Hazelcast in a Spring Boot application.

== What You’ll Learn

In this guide, you'll see how to quickly set up a Spring Boot application using Hazelcast as Hibernate's second-level cache.

== Prerequisites

In order to run the code sample, make sure to have PostgresSQL database accessible and configured properly in the `application.properties` file.

[TIP]
====
You can spin-up a PostgreSQL instance easily using Docker:
----
docker run --name 2lc-postgres --publish 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres:13
----
====

== Configuration

In order to enable JPA, you need to add a dedicated Spring Boot Starter:

----
<dependency>
    <groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
----

In order to configure Hazelcast as second-level cache provider, you need to add two dependencies:

----
<dependency>
	<groupId>com.hazelcast</groupId>
	<artifactId>hazelcast-hibernate53</artifactId>
	<version>2.0.0</version>
</dependency

<dependency>
	<groupId>com.hazelcast</groupId>
	<artifactId>hazelcast</artifactId>
	<version>4.0.2</version>
</dependency>
----

And then, we need to configure Hazelcast IMDG local member setting by adding a standard `hazelcast.xml` file into `src/main/resources`.

This will also trigger autoconfiguration of the `HazelcastInstance` bean.

The last step involves turning on second-level cache by adding two properties into `application.properties` file:

----
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=com.hazelcast.hibernate.HazelcastCacheRegionFactory
----

And now, once you annotate your entity as `@Cacheable`, it will be cached in Hazelcast member:

----
@Entity
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class Book { ... }
----

== Summary

In this guide, we bootstrapped a Spring Boot application which uses Hazelcast as Hibernate's second-level cache.

We started two application instances, and they built a Hazelcast cluster together. Since the data is shared among Hazelcast cluster instances, we can access it from both of the applications.

== See Also

- https://github.com/hazelcast-guides/caching-springboot-microservices-on-kubernetes[Caching SpringBoot Microservices with Hazelcast in Kubernetes]
- https://github.com/hazelcast-guides/caching-micronaut-microservices-on-kubernetes[Caching Micronaut microservices on Kubernetes using Hazelcast]
