:github-address: https://github.com/hazelcast-guides/springboot-hibernate
:templates-url: templates:ROOT:page$/
:hazelcast: Hazelcast IMDG
:framework: Spring Boot

= Getting Started with Hazelcast and Hibernate Second-Level Cache

This guide will get you started to use Hazelcast in a Spring Boot application.
You can see the code sample {github-address}[here].

== What You’ll Learn

In this guide, you'll see how to quickly set up a Spring Boot application using Hazelcast as Hibernate's second-level cache.

== Prerequisites

In order to run the code sample, make sure to have PostgresSQL database accessible and configured properly in the `application.properties` file.

[TIP]
====
You can spin-up a PostgreSQL instance easily using Docker:
----
docker run --name 2lc-postgres --publish 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres:13
----
====

== Configuration

In order to enable JPA, you need to add a dedicated Spring Boot Starter:

----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
----

In order to configure Hazelcast as second-level cache provider, you need to add two dependencies:

----
<dependency>
	<groupId>com.hazelcast</groupId>
	<artifactId>hazelcast-hibernate53</artifactId>
	<version>2.0.0</version>
</dependency

<dependency>
	<groupId>com.hazelcast</groupId>
	<artifactId>hazelcast</artifactId>
	<version>4.0.2</version>
</dependency>
----

And then, we need to configure Hazelcast IMDG local member setting by adding a standard `hazelcast.xml` file into `src/main/resources`.

Keep in mind that this might trigger the autoconfiguration of another Hazelcast member so you might want to disable Hazelcast autoconfiguration:

----
@SpringBootApplication(exclude = HazelcastAutoConfiguration.class)
----

The last step involves turning on second-level cache by adding two properties into `application.properties` file:

----
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=com.hazelcast.hibernate.HazelcastCacheRegionFactory
----

And now, once you annotate your entity as `@Cacheable`, it will be cached in Hazelcast member:

----
@Entity
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class Book { ... }
----
When you run the code sample, an object will be saved to database and then will be fetched. In the meantime the object will be stored in the second level cache. `SecondLevelCacheVisualizer` will print out the L2C content in every 10 seconds. The object will be evicted from the L2C after 30 seconds, which is the configured time-to-live seconds in `hazelcast.xml`.

== Summary

In this guide, we bootstrapped a Spring Boot application which uses Hazelcast as Hibernate's second-level cache.


== See Also

- xref:hibernate-jcache:ROOT:index.adoc[Using JCache for Hibernate L2C]
- xref:hazelcast-embedded-springboot:ROOT:index.adoc[Hazelcast in SpringBoot]
- xref:hazelcast-embedded-kubernetes:ROOT:index.adoc[Hazelcast with SpringBoot in Kubernetes]

